"files":
  [
    {
      "source": "/src/locales/fr.json",
      "translation": "/src/locales/%three_letters_code%.json",
      "skip_untranslated_strings":true,
      "skip_untranslated_files": true
    },
  ]
